#@TYPE: Machine
#@NAME: Polyhex Debix Model AB (i.MX 8M Plus)
#@SOC: i.MX8MP
#@DESCRIPTION: Machine configuration for Polyhex Debix Model AB with LPDDR4 4GB
#@MAINTAINER: Polyhex

require conf/machine/imx8mp-lpddr4-evk.conf

# The device tree name is implicit for LPDDR4, so can't use MACHINE here
KERNEL_DEVICETREE_BASENAME = "imx8mp-debix-io-board"

# Debix Model AB with IO board extension
KERNEL_DEVICETREE = " \
    freescale/imx8mp-debix-io-board.dtb \
"

UBOOT_DTB_NAME = "imx8mp-evk.dtb"

UBOOT_CONFIG_BASENAME = "imx8mp_evk"
UBOOT_CONFIG[sd] = "${UBOOT_CONFIG_BASENAME}_defconfig,sdcard"

# Set DDR FIRMWARE (LPDDR4)
DDR_FIRMWARE_VERSION = "202006"
DDR_FIRMWARE_NAME = " \
    lpddr4_pmu_train_1d_dmem_${DDR_FIRMWARE_VERSION}.bin \
    lpddr4_pmu_train_1d_imem_${DDR_FIRMWARE_VERSION}.bin \
    lpddr4_pmu_train_2d_dmem_${DDR_FIRMWARE_VERSION}.bin \
    lpddr4_pmu_train_2d_imem_${DDR_FIRMWARE_VERSION}.bin \
"

IMXBOOT_TARGETS_BASENAME = "flash_evk"

# Mainline BSP doesn't support LPDDR4 so it must be set to nxp.
IMX_DEFAULT_BSP = "nxp"
